Application/config/routes.rb
Rails.application.routes.draw do

  # PROFILE PRESENTATION  
  get '', to: 'pages#home'

  # FUN FACTS
  get 'sad_users', to: 'funfacts#sad_users'
  get 'popular_users', to: 'funfacts#top_users_followers'
  get 'new_users', to: 'funfacts#new_users'
  get 'ancestors', to: 'funfacts#ancestors'
  get 'oldest_issues', to: 'funfacts#oldest_issues'
  get 'new_issues', to: 'funfacts#new_issues'
  get 'popular_issues', to: 'funfacts#popular_issues'

  # Believe it or not: GitHub
  get '/believe', to: 'believes#home'

  # GitHub Compare
  get '/compare', to: 'compares#home_v1_2'
  get '/org', to: 'compares#org'

  # Contribution graph feature
  get '/contribution', to: 'contributions#home'
  get "/contribution/:username" => "contributions#generate", format: :svg
end

Application/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Application/app/controllers/believes_controller.rb
class BelievesController < ApplicationController
	
end

Application/app/controllers/compares_controller.rb
class ComparesController < ApplicationController
	
	def home_v1_2
	end

	def org
	end

end

Application/app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
	def generate
    svg = GithubChart.new(user: params["username"]).svg
		respond_to do |format|
			format.svg { render inline: svg}
		end 
  	end
end

Application/app/controllers/funfacts_controller.rb
class FunfactsController < ApplicationController

end

Application/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

Application/app/helpers/application_helper.rb
module ApplicationHelper
end

Application/app/helpers/pages_helper.rb
module PagesHelper
end

Application/app/views/believes/home.html.erb
<!doctype html>
<html>
<body>
  <div id="head">
    <h1>
      Believe it or not: GitHub 🎉 
    </h1>  
  </div>  
  <div id="data" class="clearfix">
    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">16 year-old issue found in 9 year-old GitHub using 12 year-old Git.</h3>
      <br>
      <p>An issue has been found which was formed even before GitHub was established or Git was released. Take a look at it <a href="https://github.com/cyrusimap/cyrus-sasl/issues/25">here</a></p>
      <br>
      <p>
        <img src="<%= asset_path( 'b1.png' ) %>" alt="Aditya Dancing">
      </p>
      <br>
    </div>

    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">A man who had been committing on GitHub continuously for 100 years.</h3>
      <br>
      <p>Ciro Santilli, a humble man has been commiting on GitHub for over <strong>100 years</strong>. Unfortunately, his dedication was not preceived well by others and GitHub decided to hide his contributions. Take a look at his profile <a href="https://github.com/cirosantilli">here</a></p>
      <br>
      <p>
        <img src="<%= asset_path( 'b2.png' ) %>" alt="Aditya Dancing">
      </p>
      <br>
    </div>

    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">A man who has lost his GitHub contribution graph.</h3>
      <br>
      <p>Ciro Santilli has lost his contribution graph. Take a look at his mysterious profile <a href="https://github.com/cirosantilli">here</a><br> Luckily, you can take a look at how his graph would look like now using <a href="/contribution">this feature of Repository Hunter</a></p>
      <br>
      <p>
        <img src="<%= asset_path( 'b3.png' ) %>" alt="Aditya Dancing">
      </p>
      <br>
    </div>

    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">An username extending vertically indefinitely.</h3>
      <br>
      <p>Usernames can extend vertically infinitely as well. Take a look at his mysterious profile <a href="https://github.com/goodadichat">here</a><br>
      </p>
      <br>
      <p>
        <img src="<%= asset_path( 'b4.png' ) %>" alt="Aditya Dancing">
      </p>
      <br>
    </div>

    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">A man has been on GitHub since 1991 with the highest number of followers. </h3>
      <br>
      <p>Take a look at his profile <a href="https://github.com/torvalds">here</a><br>
      </p>
      <br>
      <p>
        <img src="<%= asset_path( 'b5.png' ) %>" alt="Aditya Dancing">
      </p>
      <br>
    </div>

    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">You can make a commit on a date before your birth!</h3>
      <br>
      <p>Try out the following command: <code>git commit --date="Wed Feb 16 14:00 2011 +0100"</code><br>
      </p>
      <br>
    </div>

    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">GitHub, Inc. was originally known as Logical Awesome LLC</h3>
      <br>
      <p>Check out the present Logical Awesome LLC site
        <a href="http://logicalawesome.com/">here</a> <br>
      </p>
      <br>
      <p>
        <img src="<%= asset_path( 'b7.png' ) %>" alt="Aditya Dancing">
      </p>
      <br>
    </div>

    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">Once, GitHub was a victim.</h3>
      <br>
      <p>On 26 March 2015, GitHub fell victim to a massive distributed denial-of-service (DDOS) attack that lasted for more than 118 hours. The attack, which appeared to originate from China, primarily targeted GitHub-hosted user content describing methods of circumventing Internet censorship. <br>
      </p>
      <br>
    </div>

    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">Links to Alleged NSA Data on GitHub</h3>
      <br>
      <p>Researchers had pored over dumped data allegedly belonging to a group associated with the NSA. The data, which contains a number of working exploits, was distributed via Dropbox, MEGA, and other file sharing platforms. <br>The files were also linked to from a page on Github, but the company removed it despite having hosted plenty of hacked material in the past. It turns out that removal was not due to government pressure, but because the hacker or hackers behind the supposed breach were asking for cash to release more data. <br>
      </p>
      <br>
    </div>

    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">10,000 AWS secret access keys publically available</h3>
      <br>
      <p>Anyone who has your access key has the same level of access to your AWS resources that you do. Consequently, we go to significant lengths to protect your access keys, and in keeping with our shared-responsibility model, you should as well.
      <br> Read the article <a href="https://www.helpnetsecurity.com/2014/03/24/10000-github-users-inadvertently-reveal-their-aws-secret-access-keys/">here</a> <br>
      </p>
      <br>
    </div>

    <div style="display: inline" class="avi">
      <h3 style="font-size:20px">Over 600 private keys on GitHub for you to see.</h3>
      <br>
      <p>Github has killed its search function to safeguard users who were caught out storing keys and passwords in public repositories. 'Users found that quite a large number of users who had added private keys to their repositories and then pushed the files up to GitHub. Searching on id_rsa, a file which contains the private key for SSH logins, returned over 600 results. Projects had live configuration files from cloud services such as Amazon Web Services and Azure with the encryption keys still included. Configuration and private key files are intended to be kept secret, since if it falls into wrong hands, that person can impersonate the user (or at least, the user's machine) and easily connect to that remote machine.' Search links popped up throughout Twitter pointing to stored keys, including what was reportedly account credentials for the Google Chrome source code repository. The keys can still be found using search engines, so check your repositories.
      <br> Read the article <a href="http://thehackernews.com/2013/01/hundreds-of-ssh-private-keys-exposed.html">here</a> <br>
      </p>
      <br>
    </div>

  </div>
  
<a id="forkMe" href="https://github.com/AdiChat/Repository-Hunter">Star me on GitHub</a>
<p id="jj"><a href="https://github.com/AdiChat/Repository-Hunter/wiki/FAQ"><i class="fa fa-question-circle" aria-hidden="true"></i> Need Assistance? View FAQ</a></p>
<p id="jj1"><a href="https://github.com/AdiChat/Repository-Hunter/issues/new"><i class="fa fa-question-circle" aria-hidden="true"></i> Found something suspicious. Open an issue. </a></p>
</body>
</html>

Application/app/views/compares/home_v1_2.html.erb
        <div class='row container'>
            <div class='twelve columns'>
                <div class='row'>
                    <div class='eight columns centered center' id='title'>
                        <h3>Compare two Github accounts even though comparing is bad but it can be fun.</h3>
                    </div>
                </div>
                <form id='users'>
                    <div class='row'>
                        <div class='five columns user user1'>
                            <input type='text' name='user_1' class="login-input" value='adichat'/>
                        </div>
                        <div class='two columns vs center'>
                            <h2>💪</h2>
                        </div>

                        <div class='five columns user user2'>
                            <input type='text' name='user_2' class="login-input" value='muan'/>
                        </div>

                    </div>
                    <div class='row submit-container'>
                        <div class='six columns centered'>
                            <div id='submit' class='center'>Compare</div>
                        </div>
                    </div>
                
                </form>

                <div class='row winner-container' style='display: none;'>
                    <div class='result_1 score six columns'>
                        <h3 class='center'></h3>
                        <h2 class='center'>0</h2>
                    </div>
                    <div class='result_2 score six columns'>
                        <h3 class='center'></h3>
                        <h2 class='center'>0</h2>
                    </div>
                </div>

                <div class='row graphs-container' style='display: none;'>
                </div>
                                
            </div>
        </div>

        <a id="forkMe" href="https://github.com/AdiChat/Repository-Hunter">Star me on GitHub</a>
        
    </body>
</html>

Application/app/views/compares/org.html.erb
<style type="text/css">
table {
  margin: 0 auto;
  font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
  border-collapse: collapse;
  color: #686461;
  font-size: 30px;
}
caption {
  padding: 10px;
  color: white;
  background: #8FD4C1;
  font-size: 18px;
  text-align: left;
  font-weight: bold;
  text-align: center;
}

.head {
  border-bottom: 3px solid #B9B29F;
  padding: 10px;
  text-align: center;
  font-weight: 700;
}
td {
  padding: 10px;
  font-size: 30px;
}
tr:nth-child(odd) {
  background: white;
  font-size: 30px;
}
tr:nth-child(even) {
  background: #E8E6D1;
  font-size: 30px;
}
</style>

<script type="text/javascript">
function sorti(el) { 
   var col_sort = el.innerHTML; 
   var tr = el.parentNode;
   var table = tr.parentNode;    
   var td, arrow, col_sort_num;
   
    for (var i=0; (td = tr.getElementsByTagName("td").item(i)); i++) {
    if (td.innerHTML == col_sort) {
            col_sort_num = i; 
            if (td.prevsort == "y"){
                arrow = td.firstChild;
                el.up = Number(!el.up);
            }else{
                td.prevsort = "y";
                arrow = td.insertBefore(document.createElement("span"),td.firstChild);
                el.up = 0;
            }
            arrow.innerHTML = el.up?"↑ ":"↓ ";
        }else{
            if (td.prevsort == "y"){
                td.prevsort = "n";
                if (td.firstChild) td.removeChild(td.firstChild);
            }
        }
    }
     
     var a = new Array();
     
    for(i=1; i < table.rows.length; i++) {
        a[i-1] = new Array();
        a[i-1][0]=table.rows[i].getElementsByTagName("td").item(col_sort_num).innerHTML;
        a[i-1][1]=table.rows[i];
     }
     
     a.sort();
     if(el.up) a.reverse();  
     
     for(i=0; i < a.length; i++)
     table.appendChild(a[i][1]);
}
</script>

        <div class='row container'>
            <div class='twelve columns'>
                <div class='row'>
                    <div class='eight columns centered center' id='title'>
                        <h3>Find the best coder🏆in an organization</h3>
                    </div>
                </div>
                <form id='users'>

                  <div class='six columns centered'>
                    <input id ="organization" type='text' name='organization' class="login-input" value='github'/>
                  </div>

                    <div id="buttoncompare" class='row submit-container'>
                        <div class='six columns centered'>
                            <div id='submit' class='center'>Compare</div>
                        </div>
                    </div>
                
                </form>
                               
            </div>
        </div>

        <a id="forkMe" href="https://github.com/AdiChat/Repository-Hunter">Star me on GitHub</a>

    </body>
</html>

Application/app/views/contributions/home.html.erb
<!doctype html>
<html>

<!-- to be updated soon -->
<body>

  <div id="head">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


        <h1>Embed your Contribution Graph <font size="2"> by Repository Hunter</font></h1>
        <form>  
          <input type="text" name="username" id="username" placeholder="Enter a GitHub username and check out the contribution graph. Eg: AdiChat">    
          <button type="submit" id="submit">Get graph and embed code</button>    
        </form>
        <div id="data" class="clearfix"></div>
    <div id="piechart_3d" style="width: 900px; height: 500px;"></div>

  </div>



<script type="text/javascript">
  $(function(){
    var $username = $('#username');
    var $data = $('#data');

      $('#submit').on('click', function(e){
      e.preventDefault();
      $('#data').html('<div id="loader"><img src="<%= asset_path( 'loader.gif' ) %>" alt="loading..."></div>'); 
      var username = $username.val();
      var link1   = 'https://api.github.com/users/'+username+'';
      var link2  = 'https://api.github.com/users/'+username+'/repos'; 
      var link3 = 'https://api.github.com/repos/adichat/share/languages';   
      requestJSON(link1, function(json) {
        if(json.message === "Not Found" || username == '') {
          $data.html("<h2>The User seems to be hiding in a nutshell</h2>");
        }      
        else {
          var fullname   = json.name;
          var username   = json.login;
          var email = json.email;
          var profile = json.html_url;
          var company = json.company;
          var id = json.id;
          var face     = json.avatar_url;          
          var location   = json.location;
          var follower = json.followers;
          var following = json.following;
          var repo     = json.public_repos;
          var create_time = json.created_at;
          var update_time = json.updated_at;
          var hire = json.hireable;
          var bio = json.bio;
          var type = json.type;
          var blog = json.blog;
          var location = json.location;
          
          if( typeof fullname === 'undefined' ) { 
            fullname = username; 
          }
          
          var info = '<div class="content"><div class="avi"><a href="'+profile+'" target="_blank"><img src="'+face+'" width="80" height="80" alt="'+username+'"></a></div>';
          info = info + '<h2>'+fullname+' <span class="smallname"> , User : @<a href="'+profile+'" target="_blank">'+username+'</a></span></h2>';         

          info = info + '<p>Embed your contribution graph by placing the following code snippet in your web app:<br><strong><font size="5" color="orange"> <xmp><img src="repository-hunter.herokuapp.com/contribution/'+username+'.svg" alt="Github contribution" /></xmp></font></strong></p>';
                
          info = info + '<p>Here is your awesome contribution graph : </p><br><img src="/contribution/adichat.svg" alt="Github contribution" /><br><br>';

          

          info = info + '<p>Download your graph : <a href="/contribution/'+username+'.svg">here</a>';

          $data.html(info);
        } // end else statement

        

      }); // end requestJSON Ajax call

    

  });

    }); // end click event handler  

    function requestJSON(url, callback) {
      $.ajax({
        url: url,
        complete: function(xhr) {
          callback.call(null, xhr.responseJSON);
        }
      });
    }

    


</script>
<a id="forkMe" href="https://github.com/AdiChat/Repository-Hunter">Fork me on GitHub</a>
</html>

Application/app/views/funfacts/new_issues.html.erb
<!doctype html>
<html>

<body>
  <div id="head">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


        <form>
          <h1>
            Recently opened issues on GitHub. Let us resolve them now and show everyone our speed. 🎉 
          </h1>    
        </form>
        <div id="data" class="clearfix"></div>
  </div>
  


<script type="text/javascript">
  $(function(){
    var $username = "adichat";//$('#username');
    var $data = $('#data');
    var repol = [0,0,0,0,0,0,0];

      //$('#submit').on('click', function(e){
      //e.preventDefault();
      $('#data').html('<div id="loader"><img src="<%= asset_path( 'loader.gif' ) %>" alt="loading..."></div>'); 
      var username = "adichat";//$username.val();
      var link1   = 'https://api.github.com/search/issues?q=label:bug+state:open&sort=created&order=desc&page=1&per_page=100';

      requestJSON(link1, function(json) {
        if(json.message === "Not Found" || username == '') {
          $data.html("<h2>The User seems to be hiding in a nutshell</h2>");
        }      
        else {
                    
         var info1 = '<div style="display: inline" class="content">';
                  
          $.getJSON(link1, function(json){
            users_follow = json.items;   
            outputPageContent1();                
          });
         
          function outputPageContent1() {

            if(users_follow.length == 0) { info1 = info1 + '</div>'; }
            else {
              $.each(users_follow, function(index) {
                info1 = info1 + '<div style="display: inline" class="avi"><a href="https://github.com/'+(users_follow[index].url).substr(29)+'" target="_blank"><h3 style="font-size:20px">'+users_follow[index].title+'</h3></a><br><p>Unresolved since <strong>'+users_follow[index].created_at+'</strong></p><br><p>'+users_follow[index].body+'</p><br><p>This issue was opened by <a href="https://github.com/'+(users_follow[index].user.url).substr(29)+'">'+users_follow[index].user.login+'</a></p></div>';               
               
              });
              info1 = info1 + '</div>'; 
            }
            $data.html(info1);         
          } // end outputPageContent1()          

       } // end else statement        

      }); // end requestJSON Ajax call

    }); // end click event handler  

    function requestJSON(url, callback) {
      $.ajax({
        url: url,
        complete: function(xhr) {
          callback.call(null, xhr.responseJSON);
        }
      });
    }

    


</script>
<a id="forkMe" href="https://github.com/AdiChat/Repository-Hunter">Fork me on GitHub</a>
<p id="jj"><a href="https://github.com/AdiChat/Repository-Hunter/wiki/FAQ"><i class="fa fa-question-circle" aria-hidden="true"></i> Need Assistance? View FAQ</a></p>
<p id="jj1"><a href="https://github.com/AdiChat/Repository-Hunter/issues/new"><i class="fa fa-question-circle" aria-hidden="true"></i> Found something suspicious. Open an issue. </a></p>
</body>
</html>

Application/app/views/funfacts/new_users.html.erb
<!doctype html>
<html>

  <div id="head">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


        <form>
          <h1>
            Few new members in our family. Give them a suprise. 🎉 
          </h1>    
        </form>
        <div id="data" class="clearfix"></div>
  </div>
  


<script type="text/javascript">
  $(function(){
    var $username = "adichat";//$('#username');
    var $data = $('#data');
    var repol = [0,0,0,0,0,0,0];

      //$('#submit').on('click', function(e){
      //e.preventDefault();
      $('#data').html('<div id="loader"><img src="<%= asset_path( 'loader.gif' ) %>" alt="loading..."></div>'); 
      var username = "adichat";//$username.val();
      var link1   = 'https://api.github.com/search/users?q=type:user&sort=joined&order=desc&page=1&per_page=100';

      var link2   = 'https://api.github.com/search/users?q=type:user&sort=joined&order=desc&page=2&per_page=100';

      var link3   = 'https://api.github.com/search/users?q=type:user&sort=joined&order=desc&page=3&per_page=100';

      var link4   = 'https://api.github.com/search/users?q=type:user&sort=joined&order=desc&page=4&per_page=100';

      var info_f = "";
      
      requestJSON(link1, function(json) {
        if(json.message === "Not Found" || username == '') {
          $data.html("<h2>The User seems to be hiding in a nutshell</h2>");
        }      
        else {
                  
          $.getJSON(link1, function(json){
            users_follow = json.items;   
            outputPageContent1();                
          });
          $.getJSON(link2, function(json){
            users_follow = json.items;   
            outputPageContent1();                
          });
          $.getJSON(link3, function(json){
            users_follow = json.items;   
            outputPageContent1();                
          });
          $.getJSON(link4, function(json){
            users_follow = json.items;   
            outputPageContent1();                
          });

          function outputPageContent1() {

            var info1 = '<div>';
            if(users_follow.length == 0) { info1 = info1 + '</div>'; }
            else {
              $.each(users_follow, function(index) 
              {
                
                info1 = info1 + '<a style="display: inline" href="https://github.com/'+users_follow[index].login+'" target="_blank"><img src="'+users_follow[index].avatar_url+'" width="80" height="80" alt="'+username+'"></a>';          
              });
              info1 = info1 + '</div>'; 
              info_f = info_f + info1;
            }
            $data.html(info_f);         
          } // end outputPageContent1()

       } // end else statement

        

      }); // end requestJSON Ajax call

    

  //});

    }); // end click event handler  

    function requestJSON(url, callback) {
      $.ajax({
        url: url,
        complete: function(xhr) {
          callback.call(null, xhr.responseJSON);
        }
      });
    }

    


</script>
<a id="forkMe" href="https://github.com/AdiChat/Repository-Hunter">Fork me on GitHub</a>
<p id="jj"><a href="https://github.com/AdiChat/Repository-Hunter/wiki/FAQ"><i class="fa fa-question-circle" aria-hidden="true"></i> Need Assistance? View FAQ</a></p>
<p id="jj1"><a href="https://github.com/AdiChat/Repository-Hunter/issues/new"><i class="fa fa-question-circle" aria-hidden="true"></i> Found something suspicious. Open an issue. </a></p>
</body>
</html>

Application/app/views/funfacts/oldest_issues.html.erb
<!doctype html>
<html>

<!-- to be updated soon -->
<body>
  <div id="head">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


        <form>
          <h1>
            Oldest unresolved issues on GitHub. Let us resolve them now. 🎉 
          </h1>    
        </form>
        <div id="data" class="clearfix"></div>
  </div>
  


<script type="text/javascript">
  $(function(){
    var $username = "adichat";//$('#username');
    var $data = $('#data');
    var repol = [0,0,0,0,0,0,0];

      //$('#submit').on('click', function(e){
      //e.preventDefault();
      $('#data').html('<div id="loader"><img src="<%= asset_path( 'loader.gif' ) %>" alt="loading..."></div>'); 
      var username = "adichat";//$username.val();
      var link1   = 'https://api.github.com/search/issues?q=label:bug+state:open&sort=created&order=asc&page=1&per_page=100';

      requestJSON(link1, function(json) {
        if(json.message === "Not Found" || username == '') {
          $data.html("<h2>The User seems to be hiding in a nutshell</h2>");
        }      
        else {
                    
         var info1 = '<div style="display: inline" class="content">';
                  
          $.getJSON(link1, function(json){
            users_follow = json.items;   
            outputPageContent1();                
          });
         
          function outputPageContent1() {

            if(users_follow.length == 0) { info1 = info1 + '</div>'; }
            else {
              $.each(users_follow, function(index) {
                info1 = info1 + '<div style="display: inline" class="avi"><a href="https://github.com/'+(users_follow[index].url).substr(29)+'" target="_blank"><h3 style="font-size:20px">'+users_follow[index].title+'</h3></a><br><p>Unresolved since <strong>'+users_follow[index].created_at+'</strong></p><br><p>'+users_follow[index].body+'</p><br><p>This issue was opened by <a href="https://github.com/'+(users_follow[index].user.url).substr(29)+'">'+users_follow[index].user.login+'</a></p></div>';               
               
              });
              info1 = info1 + '</div>'; 
            }
            $data.html(info1);         
          } // end outputPageContent1()

          

       } // end else statement

        

      }); // end requestJSON Ajax call

    

  //});

    }); // end click event handler  

    function requestJSON(url, callback) {
      $.ajax({
        url: url,
        complete: function(xhr) {
          callback.call(null, xhr.responseJSON);
        }
      });
    }

    


</script>
<a id="forkMe" href="https://github.com/AdiChat/Repository-Hunter">Fork me on GitHub</a>
<p id="jj"><a href="https://github.com/AdiChat/Repository-Hunter/wiki/FAQ"><i class="fa fa-question-circle" aria-hidden="true"></i> Need Assistance? View FAQ</a></p>
<p id="jj1"><a href="https://github.com/AdiChat/Repository-Hunter/issues/new"><i class="fa fa-question-circle" aria-hidden="true"></i> Found something suspicious. Open an issue. </a></p>
<style>
#forkMe {
    top: 3em;
    right: -6em;
    color: #fff;
    display: block;
    position: fixed;
    text-align: center;
    text-decoration: none;
    letter-spacing: .06em;
    background-color: #A00;
    padding: 0.5em 5em 0.4em 5em;
    text-shadow: 0 0 0.75em #444;
    box-shadow: 0 0 0.5em rgba(0,0,0,0.5);
    transform: rotate(45deg) scale(0.75,1);
    font: bold 16px/1.2em Arial, Sans-Serif;
    -webkit-text-shadow: 0 0 0.75em #444;
    -webkit-box-shadow: 0 0 0.5em rgba(0,0,0,0.5);
    -webkit-transform: rotate(45deg) scale(0.75,1);
    z-index:10;
}
#forkMe:before {
    content: '';
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    position: absolute;
    margin: -0.3em -5em;
    transform: scale(0.7);
    -webkit-transform: scale(0.7);
    border: 2px rgba(255,255,255,0.7) dashed;
}
#forkMe:hover {opacity: 0.9;}
#jj {
  position: fixed;
  bottom: 0;
  right: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
  align-content: center;
  margin: 0;
  padding: 5px;
  background-color: grey;
  a {
    color: white;
    text-decoration: none;
    &:hover { text-decoration: none; }
  }
}
#jj1 {
  position: fixed;
  bottom: 0;
  left: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
  align-content: center;
  margin: 0;
  padding: 5px;
  background-color: grey;
  a {
    color: white;
    text-decoration: none;
    &:hover { text-decoration: none; }
  }
}
</style>
</body>
</html>

Application/app/views/layouts/application.html.erb
<% if current_page?(org_path) %>
    <%= render 'layouts/org' %>
<% elsif current_page?(compare_path) %>
	<%= render 'layouts/battle' %>
<% else %>
    <%= render 'layouts/head' %>
<% end %>